CREATE TABLE sales (
    id SERIAL PRIMARY KEY,
    customer_first_name VARCHAR(255),
    customer_last_name VARCHAR(255),
    customer_age INT,
    customer_email VARCHAR(255),
    customer_country VARCHAR(255),
    customer_postal_code VARCHAR(255) NULL,
    customer_pet_type VARCHAR(255),
    customer_pet_name VARCHAR(255),
    customer_pet_breed VARCHAR(255),
    
    seller_first_name VARCHAR(255),
    seller_last_name VARCHAR(255),
    seller_email VARCHAR(255),
    seller_country VARCHAR(255),
    seller_postal_code VARCHAR(255) NULL,
    
    product_name VARCHAR(255),
    product_category VARCHAR(255),
    product_price DOUBLE PRECISION,
    product_quantity INT,
    
    sale_date VARCHAR(255),
    sale_customer_id INT,
    sale_seller_id INT,
    sale_product_id INT,
    sale_quantity INT,
    sale_total_price DOUBLE PRECISION,
    
    store_name VARCHAR(255),
    store_location VARCHAR(255),
    store_city VARCHAR(255),
    store_state VARCHAR(255) NULL,
    store_country VARCHAR(255),
    store_phone VARCHAR(255),
    store_email VARCHAR(255),
    
    pet_category VARCHAR(255),
    product_weight DOUBLE PRECISION,
    product_color VARCHAR(255),
    product_size VARCHAR(255),
    product_brand VARCHAR(255),
    product_material VARCHAR(255),
    product_description TEXT,
    
    product_rating DOUBLE PRECISION,
    product_reviews INT,
    product_release_date VARCHAR(255),
    product_expiry_date VARCHAR(255),
    
    supplier_name VARCHAR(255),
    supplier_contact VARCHAR(255),
    supplier_email VARCHAR(255),
    supplier_phone VARCHAR(255),
    supplier_address VARCHAR(255),
    supplier_city VARCHAR(255),
    supplier_country VARCHAR(255)
);
